services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ghumdoza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata: