spring.application.name=GhumDoZa

spring.datasource.url=jdbc:postgresql://db:5432/ghumdoza
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

openai.on=false
#openai.model=gpt-3.5-turbo
#openai.api.url=https://api.openai.com/v1/chat/completions